// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Hoge$YourProjectName from "./hoge.bs.js";
import * as Board$YourProjectName from "./board.bs.js";

function Game(Props) {
  return React.createElement("div", {
              className: "game"
            }, React.createElement("div", {
                  className: "game-board"
                }, React.createElement(Board$YourProjectName.make, {})), React.createElement("div", undefined, React.createElement(Hoge$YourProjectName.make, {
                      name: "1234"
                    })));
}

var make = Game;

export {
  make ,
  
}
/* react Not a pure module */
