// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as React from "react";

function Hoge(Props) {
  var name = Props.name;
  return React.createElement("div", undefined, "hogehoge" + (name + name));
}

var make = Hoge;

export {
  make ,
  
}
/* react Not a pure module */
